services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  pulsar:
    image: apachepulsar/pulsar
    command: >
      bash -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres-data:
